### ISSUE TITLE
Barber is incompatible with Dagger code generation

### ISSUE THREAD

**Issue by inktomi** [hzsweers/barber#6]
Hi - 

Tracking this, so I wanted to put in an issue. When adding Barber to a project that already uses Dagger (and dagger-compiler) for injection, dagger code generation fails to run. 

My setup is as such;

```
apt 'io.sweers.barber:barber-compiler:1.0.1'
compile 'io.sweers.barber:barber-api:1.0.1'
compile 'com.squareup.dagger:dagger:1.2.2'
provided 'com.squareup.dagger:dagger-compiler:1.2.2'
```

**Comment by hzsweers** [comment]
Can you give me a little more info? Stacktrace, does it happen even if you don't use any barber code, etc?

**Comment by ZacSweers** [comment]
Can you give me a little more info? Everything still builds just fine for me if I add dagger to my dependencies. A stacktrace would be useful.

**Comment by denley** [comment]
If more than one annotation processor is used then this also has to be added to the build config:

``` groovy
android {
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
```

You should get a warning about this though, so perhaps the issue is elsewhere.

**Comment by ZacSweers** [comment]
Ah yes, that's a good point. Would be better if @inktomi could provide some more clarification though

**Comment by inktomi** [comment]
I'm so sorry. I've been out of town. I will try this tomorrow on a fresh project to ensure there was nothing else happening in mine..

**Comment by ZacSweers** [comment]
Sounds good, thanks!

**Comment by ZacSweers** [comment]
@inktomi any luck?

**Comment by inktomi** [comment]
Hi, sorry for the delay.

I set up the following little test project. It shows the issue when you try to run it. 

https://github.com/inktomi/BarberDagger

```
03-09 09:15:22.008    5388-5388/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mattruno.testdaggerbarber, PID: 5388
    java.lang.RuntimeException: Unable to create application com.mattruno.testdaggerbarber.TestApplication: java.lang.IllegalStateException: Module adapter for class com.mattruno.testdaggerbarber.ServiceModule could not be loaded. Please ensure that code generation was run for this module.
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalStateException: Module adapter for class com.mattruno.testdaggerbarber.ServiceModule could not be loaded. Please ensure that code generation was run for this module.
            at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:45)
            at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:40)
            at dagger.internal.Memoizer.get(Memoizer.java:56)
            at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:57)
            at dagger.internal.Modules.loadModules(Modules.java:43)
            at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:174)
            at dagger.ObjectGraph$DaggerObjectGraph.access$000(ObjectGraph.java:138)
            at dagger.ObjectGraph.create(ObjectGraph.java:129)
            at com.mattruno.testdaggerbarber.TestApplication.onCreate(TestApplication.java:16)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by ZacSweers** [comment]
I see. Have you tried @denley's solution? I'm not very familiar with Dagger, so I'm not sure where to start with this since all the code looks like it's just dagger issues.

```
android {
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
```

**Comment by inktomi** [comment]
I do have that included in the gradle file for the app module.. no affect though =\

https://github.com/inktomi/BarberDagger/blob/master/app/build.gradle

**Comment by ZacSweers** [comment]
Hmm, I have no idea then. I'll try looking at it some this weekend, but no promises. Going to mark this as help wanted now as well

**Comment by denley** [comment]
I just had a quick look and I think I've figured it out. It's actually not an issue with Barber (the same problem occurs when you remove the Barber dependencies). It appears to be an issue with the android-apt plugin ignoring the `provided` dependencies.

It will work with the following configuration instead (notice the `apt` instead of `provided` for the dagger compiler dependency):

``` groovy
apt 'io.sweers.barber:barber-compiler:1.0.1'
compile 'io.sweers.barber:barber-api:1.0.1'
compile 'com.squareup.dagger:dagger:1.2.2'
apt 'com.squareup.dagger:dagger-compiler:1.2.2'
```

**Comment by ZacSweers** [comment]
Ah interesting, so someone can't use `apt` and `provided` in the same configuration?

**Comment by denley** [comment]
It appears that way. The apt plugin seems to completely take over the annotation processing or something like that.

**Comment by ZacSweers** [comment]
Interesting. Well, good to know. @inktomi can I mark this as resolved then?

**Comment by inktomi** [comment]
Awesome. Thanks for the team effort!!
